### ISSUE TITLE
Create Jackadull-Meta release/latest Branch

### ISSUE THREAD

**Issue by Madoc** [jackadull/jackadull-meta#2]
After the first release:
- [ ] [Protect the `release/next` branch further][next-release-branch-settings], by enabling the Travis-CI status check.
- [ ] Create the `release/latest` branch.
- [ ] Set it as the default branch.
- [ ] Protect the branch.
- [ ] Enable the branch in CodeFactor.
- [ ] Add the project to [Snyk][snyk].

[next-release-branch-settings]: ../settings/branches/release%2Fnext
[snyk]: https://snyk.io
